# Generated by Django 2.1.3 on 2018-12-06 11:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='desc',
            field=ckeditor.fields.RichTextField(default='', verbose_name='机构描述'),
        ),
    ]
