# Generated by Django 2.1.3 on 2018-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_desc'),
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='organization.Teacher', verbose_name='讲师'),
        ),
    ]
